/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package component;
import DBConnection.DatabaseConnection;
import Model.ModelUser;
import component.Animation3;
import java.awt.Color;
import java.sql.*;
import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author acer
 */
public class ComingSoon extends javax.swing.JFrame {
    Animation3 ColorOP = new Animation3();
    /**
     * Creates new form BookForm
     */
    public ComingSoon() {
        
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        ColorOP.AnimateFood3();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel1 = new swing.Panel();
        panelClass2 = new component.PanelClass();
        labelwelcome1 = new javax.swing.JLabel();
        labelwelcome = new javax.swing.JLabel();
        paneldetail3 = new component.PanelGradient();
        labeldetail3 = new javax.swing.JLabel();
        panelbook3 = new component.PanelGradient();
        labelbook3 = new javax.swing.JLabel();
        panelfood3 = new component.PanelGradient();
        labelfood3 = new javax.swing.JLabel();
        panelhome3 = new component.PanelGradient();
        labelhome3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelClass2.setBackground(new java.awt.Color(23, 27, 36));
        panelClass2.setPreferredSize(new java.awt.Dimension(222, 554));

        labelwelcome1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelwelcome1.setForeground(new java.awt.Color(255, 255, 255));
        labelwelcome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelwelcome1.setText("DKH CINEMA");

        labelwelcome.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        labelwelcome.setForeground(new java.awt.Color(255, 255, 255));
        labelwelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelwelcome.setText("Welcome To ");

        paneldetail3.setBackground(new java.awt.Color(23, 27, 36));
        paneldetail3.setToolTipText("");
        paneldetail3.setAlignmentX(0.0F);
        paneldetail3.setAlignmentY(0.0F);
        paneldetail3.setColorGradient(new java.awt.Color(23, 27, 36));
        paneldetail3.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        paneldetail3.setMinimumSize(new java.awt.Dimension(180, 40));
        paneldetail3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paneldetail3MousePressed(evt);
            }
        });
        paneldetail3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labeldetail3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labeldetail3.setForeground(new java.awt.Color(166, 166, 166));
        labeldetail3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeldetail3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/detail.png"))); // NOI18N
        labeldetail3.setText("Booking Detail");
        labeldetail3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeldetail3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labeldetail3MousePressed(evt);
            }
        });
        paneldetail3.add(labeldetail3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 40));

        panelbook3.setBackground(new java.awt.Color(23, 27, 36));
        panelbook3.setToolTipText("");
        panelbook3.setAlignmentX(0.0F);
        panelbook3.setAlignmentY(0.0F);
        panelbook3.setColorGradient(new java.awt.Color(23, 27, 36));
        panelbook3.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        panelbook3.setMinimumSize(new java.awt.Dimension(180, 40));
        panelbook3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelbook3MousePressed(evt);
            }
        });
        panelbook3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelbook3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelbook3.setForeground(new java.awt.Color(166, 166, 166));
        labelbook3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelbook3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/books.png"))); // NOI18N
        labelbook3.setText("Book");
        labelbook3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelbook3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelbook3MousePressed(evt);
            }
        });
        panelbook3.add(labelbook3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelfood3.setBackground(new java.awt.Color(23, 27, 36));
        panelfood3.setToolTipText("");
        panelfood3.setAlignmentX(0.0F);
        panelfood3.setAlignmentY(0.0F);
        panelfood3.setColorGradient(new java.awt.Color(23, 27, 36));
        panelfood3.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        panelfood3.setMinimumSize(new java.awt.Dimension(180, 40));
        panelfood3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelfood3MousePressed(evt);
            }
        });
        panelfood3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelfood3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelfood3.setForeground(new java.awt.Color(166, 166, 166));
        labelfood3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelfood3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/comingsoon.png"))); // NOI18N
        labelfood3.setText("Coming Soon");
        labelfood3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelfood3MousePressed(evt);
            }
        });
        panelfood3.add(labelfood3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelhome3.setBackground(new java.awt.Color(23, 27, 36));
        panelhome3.setToolTipText("");
        panelhome3.setAlignmentX(0.0F);
        panelhome3.setAlignmentY(0.0F);
        panelhome3.setColorGradient(new java.awt.Color(23, 27, 36));
        panelhome3.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        panelhome3.setMinimumSize(new java.awt.Dimension(180, 40));
        panelhome3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelhome3MousePressed(evt);
            }
        });
        panelhome3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelhome3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelhome3.setForeground(new java.awt.Color(166, 166, 166));
        labelhome3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelhome3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/home.png"))); // NOI18N
        labelhome3.setText("Home");
        labelhome3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelhome3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelhome3MousePressed(evt);
            }
        });
        panelhome3.add(labelhome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        javax.swing.GroupLayout panelClass2Layout = new javax.swing.GroupLayout(panelClass2);
        panelClass2.setLayout(panelClass2Layout);
        panelClass2Layout.setHorizontalGroup(
            panelClass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClass2Layout.createSequentialGroup()
                .addGroup(panelClass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClass2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(labelwelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelClass2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelhome3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelClass2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelbook3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelClass2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelfood3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelClass2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(paneldetail3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClass2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelwelcome1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        panelClass2Layout.setVerticalGroup(
            panelClass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClass2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(labelwelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(labelwelcome1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(panelhome3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelbook3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelfood3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paneldetail3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(40, 62, 81));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cs2.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cs3.png"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cs1.png"))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cs4.png"))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cs5.png"))); // NOI18N

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cs6.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("The Amateur");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Dog Man");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Inheritance");

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Captain America");

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("The Lord of the Rings");

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Solo Leveling");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(169, 169, 169)
                .addComponent(jLabel9)
                .addGap(96, 96, 96))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel10)
                .addGap(115, 115, 115)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(81, 81, 81))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(panelClass2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelClass2, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelhome3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelhome3MousePressed
        // TODO add your handling code here:
        ColorOP.AnimateHome3();
    }//GEN-LAST:event_labelhome3MousePressed

    private void panelhome3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelhome3MousePressed
        // TODO add your handling code here:
        ColorOP.AnimateHome3();
    }//GEN-LAST:event_panelhome3MousePressed

    private void labelbook3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbook3MousePressed
        // TODO add your handling code here:
        ColorOP.AnimateBook3();
    }//GEN-LAST:event_labelbook3MousePressed

    private void panelbook3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbook3MousePressed
        // TODO add your handling code here:
        ColorOP.AnimateBook3();
    }//GEN-LAST:event_panelbook3MousePressed

    private void labelfood3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelfood3MousePressed
        // TODO add your handling code here:
        ColorOP.AnimateFood3();
    }//GEN-LAST:event_labelfood3MousePressed

    private void panelfood3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelfood3MousePressed
        // TODO add your handling code here:
        ColorOP.AnimateFood3();
    }//GEN-LAST:event_panelfood3MousePressed

    private void labeldetail3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeldetail3MousePressed
        // TODO add your handling code here:
        ColorOP.AnimateDetail3();
    }//GEN-LAST:event_labeldetail3MousePressed

    private void paneldetail3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneldetail3MousePressed
        // TODO add your handling code here:
        ColorOP.AnimateDetail3();
    }//GEN-LAST:event_paneldetail3MousePressed

    private void labelhome3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelhome3MouseClicked
        // TODO add your handling code here:
        ModelUser user = new ModelUser();
        DashBoard df = new DashBoard(user);
        df.setLocation(this.getLocation());
        df.setVisible(true);
        dispose();
    }//GEN-LAST:event_labelhome3MouseClicked

    private void labelbook3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbook3MouseClicked
        // TODO add your handling code here:
        BookForm bf = new  BookForm();
        bf.setLocation(this.getLocation());
        bf.setVisible(true);
        dispose();
    }//GEN-LAST:event_labelbook3MouseClicked

    private void labeldetail3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeldetail3MouseClicked
        // TODO add your handling code here:
        BookingDetail bd = new  BookingDetail();
        bd.setLocation(this.getLocation());
        bd.setVisible(true);
        dispose();
    }//GEN-LAST:event_labeldetail3MouseClicked
    
    

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComingSoon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComingSoon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComingSoon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComingSoon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComingSoon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel labelbook3;
    public static javax.swing.JLabel labeldetail3;
    public static javax.swing.JLabel labelfood3;
    public static javax.swing.JLabel labelhome3;
    private javax.swing.JLabel labelwelcome;
    private javax.swing.JLabel labelwelcome1;
    private swing.Panel panel1;
    private component.PanelClass panelClass2;
    public static component.PanelGradient panelbook3;
    public static component.PanelGradient paneldetail3;
    public static component.PanelGradient panelfood3;
    public static component.PanelGradient panelhome3;
    // End of variables declaration//GEN-END:variables
}
