/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package component;
import Model.ModelUser;
import component.Animation;
import component.BookForm;
import java.awt.Color;
import test.Slide1;
import test.Slide2;
import test.Slide3;
import test.Slide4;
import test.Slide5;
import test.Slide6;
import test.Slide7;


/**
 *
 * @author acer
 */
public class DashBoard extends javax.swing.JFrame {
    private final ModelUser user;
    Animation ColorOP = new Animation();

    public DashBoard(ModelUser user) {
        this.user=user;
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        ColorOP.AnimateHome();
        getContentPane().setBackground(new Color(23,27,36));
        slideshow1.initSlideshow(new Slide1(), new Slide2(),new Slide3(), new Slide4(), new Slide5(), new Slide6(), new Slide7());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelhome2 = new component.PanelGradient();
        labelhome2 = new javax.swing.JLabel();
        panel1 = new swing.Panel();
        panelClass1 = new component.PanelClass();
        labelwelcome1 = new javax.swing.JLabel();
        paneldetail = new component.PanelGradient();
        labeldetail = new javax.swing.JLabel();
        panelfood = new component.PanelGradient();
        labelfood = new javax.swing.JLabel();
        panelbook = new component.PanelGradient();
        labelbook = new javax.swing.JLabel();
        panelhome = new component.PanelGradient();
        labelhome = new javax.swing.JLabel();
        labelwelcome = new javax.swing.JLabel();
        slideshow1 = new slideshow.Slideshow();
        jScrollPane2 = new javax.swing.JScrollPane();
        movie1 = new component.Movie();

        panelhome2.setBackground(new java.awt.Color(52, 100, 174));
        panelhome2.setColorGradient(new java.awt.Color(59, 207, 255));
        panelhome2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelhome2MousePressed(evt);
            }
        });
        panelhome2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelhome2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelhome2.setForeground(new java.awt.Color(255, 255, 255));
        labelhome2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelhome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/home.png"))); // NOI18N
        labelhome2.setText("Home");
        labelhome2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelhome2MousePressed(evt);
            }
        });
        panelhome2.add(labelhome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel1.setBackground(new java.awt.Color(29, 47, 61));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelClass1.setBackground(new java.awt.Color(23, 27, 36));
        panelClass1.setPreferredSize(new java.awt.Dimension(222, 554));

        labelwelcome1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelwelcome1.setForeground(new java.awt.Color(255, 255, 255));
        labelwelcome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelwelcome1.setText("DKH CINEMA");

        paneldetail.setBackground(new java.awt.Color(23, 27, 36));
        paneldetail.setColorGradient(new java.awt.Color(23, 27, 36));
        paneldetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paneldetailMousePressed(evt);
            }
        });
        paneldetail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labeldetail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labeldetail.setForeground(new java.awt.Color(166, 166, 166));
        labeldetail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeldetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/detail.png"))); // NOI18N
        labeldetail.setText("Booking Detail");
        labeldetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeldetailMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labeldetailMousePressed(evt);
            }
        });
        paneldetail.add(labeldetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        panelfood.setBackground(new java.awt.Color(23, 27, 36));
        panelfood.setColorGradient(new java.awt.Color(23, 27, 36));
        panelfood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelfoodMousePressed(evt);
            }
        });
        panelfood.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelfood.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelfood.setForeground(new java.awt.Color(166, 166, 166));
        labelfood.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelfood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/food.png"))); // NOI18N
        labelfood.setText("Coming Soon");
        labelfood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelfoodMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelfoodMousePressed(evt);
            }
        });
        panelfood.add(labelfood, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 40));

        panelbook.setBackground(new java.awt.Color(23, 27, 36));
        panelbook.setColorGradient(new java.awt.Color(23, 27, 36));
        panelbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelbookMousePressed(evt);
            }
        });
        panelbook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelbook.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelbook.setForeground(new java.awt.Color(166, 166, 166));
        labelbook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelbook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/books.png"))); // NOI18N
        labelbook.setText("Book");
        labelbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelbookMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelbookMousePressed(evt);
            }
        });
        panelbook.add(labelbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 190, 40));

        panelhome.setBackground(new java.awt.Color(23, 27, 36));
        panelhome.setColorGradient(new java.awt.Color(23, 27, 36));
        panelhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelhomeMousePressed(evt);
            }
        });
        panelhome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelhome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelhome.setForeground(new java.awt.Color(166, 166, 166));
        labelhome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/home.png"))); // NOI18N
        labelhome.setText("Home");
        labelhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelhomeMousePressed(evt);
            }
        });
        panelhome.add(labelhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        labelwelcome.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        labelwelcome.setForeground(new java.awt.Color(255, 255, 255));
        labelwelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelwelcome.setText("Welcome To ");

        javax.swing.GroupLayout panelClass1Layout = new javax.swing.GroupLayout(panelClass1);
        panelClass1.setLayout(panelClass1Layout);
        panelClass1Layout.setHorizontalGroup(
            panelClass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClass1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(labelwelcome1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(panelClass1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(labelwelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelClass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelClass1Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(panelClass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(paneldetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelfood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelbook, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelhome, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        panelClass1Layout.setVerticalGroup(
            panelClass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClass1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(labelwelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelwelcome1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelClass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelClass1Layout.createSequentialGroup()
                    .addGap(162, 162, 162)
                    .addComponent(panelhome, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(panelbook, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(panelfood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(paneldetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panel1.add(panelClass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 590));
        panel1.add(slideshow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 750, 190));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setOpaque(false);
        jScrollPane2.setViewportView(movie1);

        panel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 750, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labelhomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelhomeMousePressed
        // TODO add your handling code here:
        ColorOP.AnimateHome();
    }//GEN-LAST:event_labelhomeMousePressed

    private void panelhomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelhomeMousePressed
        // TODO add your handling code here:
        ColorOP.AnimateHome();
    }//GEN-LAST:event_panelhomeMousePressed

    private void labelbookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbookMousePressed
        // TODO add your handling code here:
        ColorOP.AnimateBook();
    }//GEN-LAST:event_labelbookMousePressed

    private void panelbookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbookMousePressed
        // TODO add your handling code here:
        ColorOP.AnimateBook();
    }//GEN-LAST:event_panelbookMousePressed

    private void labelhome2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelhome2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelhome2MousePressed

    private void panelhome2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelhome2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelhome2MousePressed

    private void labelfoodMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelfoodMousePressed
        // TODO add your handling code here:
        ColorOP.AnimateFood();
    }//GEN-LAST:event_labelfoodMousePressed

    private void panelfoodMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelfoodMousePressed
        // TODO add your handling code here:
        ColorOP.AnimateFood();
    }//GEN-LAST:event_panelfoodMousePressed

    private void labeldetailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeldetailMousePressed
        // TODO add your handling code here:
        ColorOP.AnimateDetail();
    }//GEN-LAST:event_labeldetailMousePressed

    private void paneldetailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneldetailMousePressed
        // TODO add your handling code here:
        ColorOP.AnimateDetail();
    }//GEN-LAST:event_paneldetailMousePressed

    private void labelbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelbookMouseClicked
        // TODO add your handling code here:
        BookForm bf = new BookForm();
        bf.setLocation(this.getLocation());
        bf.setVisible(true);
        dispose();
    }//GEN-LAST:event_labelbookMouseClicked

    private void labeldetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeldetailMouseClicked
        // TODO add your handling code here:
        BookingDetail bd = new BookingDetail();
        bd.setLocation(this.getLocation());
        bd.setVisible(true);
        dispose();
    }//GEN-LAST:event_labeldetailMouseClicked

    private void labelfoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelfoodMouseClicked
        // TODO add your handling code here:
        ComingSoon cs = new  ComingSoon();
        cs.setLocation(this.getLocation());
        cs.setVisible(true);
        dispose();
    }//GEN-LAST:event_labelfoodMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(ModelUser user) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard(user).setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel labelbook;
    public static javax.swing.JLabel labeldetail;
    public static javax.swing.JLabel labelfood;
    public static javax.swing.JLabel labelhome;
    private javax.swing.JLabel labelhome2;
    private javax.swing.JLabel labelwelcome;
    private javax.swing.JLabel labelwelcome1;
    private component.Movie movie1;
    private swing.Panel panel1;
    private component.PanelClass panelClass1;
    public static component.PanelGradient panelbook;
    public static component.PanelGradient paneldetail;
    public static component.PanelGradient panelfood;
    public static component.PanelGradient panelhome;
    private component.PanelGradient panelhome2;
    private slideshow.Slideshow slideshow1;
    // End of variables declaration//GEN-END:variables
}
