/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;
import component.TrendFilm;
import javax.swing.ImageIcon;
/**
 *
 * @author acer
 */
public class Movie extends javax.swing.JPanel {

    /**
     * Creates new form Movie
     */
    public Movie() {
        initComponents();
        init();
    }
    
     private void init() {
        trendingMovie.addImage(new TrendFilm(new ImageIcon(getClass().getResource("/Icon/movie1.png")), "", "PG-13"));
        trendingMovie.addImage(new TrendFilm(new ImageIcon(getClass().getResource("/Icon/movie2.png")), "", "R"));
        trendingMovie.addImage(new TrendFilm(new ImageIcon(getClass().getResource("/Icon/movie3.png")), "", "R"));
        trendingMovie.addImage(new TrendFilm(new ImageIcon(getClass().getResource("/Icon/movie4.png")), "", "PG-13"));
        trendingMovie.addImage(new TrendFilm(new ImageIcon(getClass().getResource("/Icon/movie5.png")), "", "R"));
        trendingMovie.addImage(new TrendFilm(new ImageIcon(getClass().getResource("/Icon/movie6.png")), "", "R"));
        trendingMovie.addImage(new TrendFilm(new ImageIcon(getClass().getResource("/Icon/movie7.png")), "", "PG-13"));
        trendingMovie.addImage(new TrendFilm(new ImageIcon(getClass().getResource("/Icon/movie8.png")), "", "R"));
        trendingMovie.addImage(new TrendFilm(new ImageIcon(getClass().getResource("/Icon/movie9.png")), "", "PG"));
        trendingMovie.addImage(new TrendFilm(new ImageIcon(getClass().getResource("/Icon/movie10.png")), "", "PG"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        trendingMovie = new component.TrendingMovie();

        setBackground(new java.awt.Color(40, 62, 81));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Now Showing");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trendingMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trendingMovie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private component.TrendingMovie trendingMovie;
    // End of variables declaration//GEN-END:variables
}
